print('=========DESAFIO04=========')
n = input(print('Digite algo'))
print('O tipo primitivo que voce digitou?', type(n))
print('O que voce digitou só tem espaço? '.format(n.isspace()))
print('O que voce digitou é númerico? {}'.format(n.isnumeric()))
print('O que voce digitou é uma string? {}'.format(n.isalpha()))
print('O que voce digitou é alfanúmerico? {}'.format(n.isalnum()))
print('O que voce digitou ta todo em maiusculo? {}'.format(n.isupper()))
print('O que voce digitou ta todo em minúscula? {}'.format(n.islower()))
